# Pytorch 

In [5]:
import numpy as np
import torch
import torchvision
import torchvision.transforms as transforms

## Tensors

Specialized data structure. Similar to arrays or matrices. Simlar to numpy arrays except that these can run on GPUs or other hardware accelerators.

Used to encode the inputs and outputs of a model, as well as the model's parameters.

Create from `torch` with `torch.tensor()`. Numpy is similar with creation from `np` or the package name, and then `np.array()`.

It has methods we can call on it. It has attributes. (Because like other objects, it has function defined and variables stored within it; we can think of it in this way as designed as a class or struct).

In [4]:
# directly instantiate tensor from native data structures
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
data

[[1, 2], [3, 4]]

In [6]:
# from numpy array
data_np = np.array(data)
data_np

array([[1, 2],
       [3, 4]])

In [11]:
# other methods
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3233, 0.1820, 0.8653],
        [0.4579, 0.7938, 0.2758]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# some attributes of tensors
print(f"tensor shape {rand_tensor.shape}")
print(f"tensor type {rand_tensor.dtype}")
print(f"tensor storage device {rand_tensor.device}")

tensor shape torch.Size([2, 3])
tensor type torch.float32
tensor storage device cpu


In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [18]:
# has standard numpy like indexing
print(rand_tensor)
print()
print(rand_tensor[1])
print()
print(rand_tensor[:, -2])

tensor([[0.3233, 0.1820, 0.8653],
        [0.4579, 0.7938, 0.2758]])

tensor([0.4579, 0.7938, 0.2758])

tensor([0.1820, 0.7938])


In [23]:
# joining tensors
# dim=0 means rows because in matrics the dimension is rxc
# dim=1 means cols
joined_tensor_along_rows = torch.concat([rand_tensor, ones_tensor], dim=0)
print(joined_tensor_ along_rows)

tensor([[0.3233, 0.1820, 0.8653],
        [0.4579, 0.7938, 0.2758],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])


In [25]:

joined_tensor_along_cols = torch.concat([rand_tensor, ones_tensor], dim=1)
print(joined_tensor_along_cols)

tensor([[0.3233, 0.1820, 0.8653, 1.0000, 1.0000, 1.0000],
        [0.4579, 0.7938, 0.2758, 1.0000, 1.0000, 1.0000]])


In [28]:
y1 = rand_tensor @ rand_tensor.T

In [30]:
print(rand_tensor)
print(y1)
y1

tensor([[0.3233, 0.1820, 0.8653],
        [0.4579, 0.7938, 0.2758]])
tensor([[0.8864, 0.5312],
        [0.5312, 0.9159]])


tensor([[0.8864, 0.5312],
        [0.5312, 0.9159]])

In [33]:
t1 = torch.tensor([[1,1],[2,2]])
t2 = torch.tensor([[1,1],[2,2]])
print(t1)
print(t2)

tensor([[1, 1],
        [2, 2]])
tensor([[1, 1],
        [2, 2]])


In [37]:
# matrix mult
t1 @ t2

tensor([[3, 3],
        [6, 6]])

In [38]:
# also matrix mult
t1.matmul(t2)

tensor([[3, 3],
        [6, 6]])

In [39]:
# element wise product
t1 * t2
t1.mul(t2)

tensor([[1, 1],
        [4, 4]])

In [42]:
# add all elements
print(t1)
agg = t1.sum()
agg # 1 + 1 + 2 + 2 = 6

tensor([[1, 1],
        [2, 2]])


tensor(6)